### ISSUE TITLE
Request: AzPainter

### ISSUE THREAD

**Issue by Symbian9** [haikuports/haikuports#2499]
Hi, Haiku porters!

Take a look on *AzPainter* (for Unix-like systems) -- full color painting software for illustration drawing

- https://github.com/Symbian9/azpainter

![AzPainter](http://i.imgur.com/A7izgWn.png)

### TODO

Please, port it to Haiku OS! (if possible)

- [ ] https://github.com/Symbian9/azpainter/issues/37
- [ ] https://github.com/Symbian9/azpainter/issues/40
- [ ] https://github.com/haikuports/haikuports/tree/master/media-gfx/azpainter

### REFERENCE

- https://github.com/Symbian9/azpainter/wiki/Packaging-status

**Comment by extrowerk** [comment]
Haiku have no X11 support, yet.

**Comment by fbrosson** [comment]
We have recipes for all the libs which seem to be needed, so I think we can write a recipe for AzPainter.

**Comment by extrowerk** [comment]
I just built it to make sure.

```
/Ports/Inst/az/bin > ls
azpainter
/Ports/Inst/az/bin > objdump -x azpainter | grep NEEDED
  NEEDED               libX11.so.6
  NEEDED               libXext.so.6
  NEEDED               libfontconfig.so.1
  NEEDED               libfreetype.so.6
  NEEDED               libpng16.so.16
  NEEDED               libjpeg.so.9
  NEEDED               libz.so.1
  NEEDED               libXi.so.6
  NEEDED               libroot.so
/Ports/Inst/az/bin > ./azpainter 
failed XOpenDisplay()
/Ports/Inst/az/bin >
```
X server required. We got none.

**Comment by fbrosson** [comment]
Well, you could run AzPainter and have the it contact a remote X11 server :)

I guess a "ssh -X yourHaikuSystem" from a Linux box would allow to display AzPainter on your Linux server.

That said, I do admit that it would not be very useful.

**Comment by Symbian9** [comment]
Fixed!

- https://github.com/haikuports/haikuports/issues/2906#issuecomment-1020431202
