### ISSUE TITLE
[Python packages]: some packages install with the wrong version (or wrong name)

### ISSUE THREAD

**Issue by OscarL** [haikuports/haikuports#7962]
While doing some testing (and cleanup) after the recipes updates for the Python versions, I've came across some packages that cause issues with pip dependencies resolution, because they somehow ended up with their versions set to `0.0.0`. The affected packages I could find in my systems are:

- importlib_metadata-0.0.0
- pytest-0.0.0
- zipp-0.0.0

And even weirded, the `more_itertools` package ended up with the name-version `UKNOWN-0.0.0`.

As a quick test, I've tried rebuilding `zipp` locally (to see if a rebuild with the updated/fixed Python versions would help) and it does still ends with that 0.0.0 version. Haven't investigated further.

Opening this issue to keep track of these, and others that people may come across.

---

**EDIT**: "Final" list of packages with wrong versions ("0.0.0" or "0.1-dev.xxx") on `pip list`, and their corresponding PRs:

- [x] argon2_cffi_bindings: #7990
- [x] automat: #7991
- [x] importlib_metadata #8003
- [x] importlib_resources #8002
- [x] lazy_object_proxy: #7992
- [x] more_itertools (name=UNKNOWN) #8006
- [x] pluggy: #7993
- [x] py: #7994 (or #8004)
- [x] pytest #8005
- [x] zipp #8001

---

Edit 2: For the record... the issue was caused by `setuptools_scm` missing `toml` and `cmd:git` dependencies, and some packages needing the `SETUPTOOLS_SCM_PRETEND_VERSION` variable set.

---

Edit 3:

~~Still no idea about how to fix `more_itertools`~~. Still ends in a package with no ".py" files in it, with empty files like `UNKNOWN-0.0.0-py3.9.egg-info`.

Proposed fix for this: #8006.

**Comment by Begasus** [comment]
Could you check?

- [ ] argon2_cffi_bindings: https://build.haiku-os.org/buildmaster/master/x86_64/?buildrunDir=&viewMode=expanded

**Comment by Begasus** [comment]
Without the PR:
`Copying py.egg-info to /packages/py-1.11.0-3/.self/lib/python3.10/vendor-packages/py-0.1.dev1+g749c270.d20230319-py3.10.egg-info`
With the PR:
`Copying py.egg-info to /packages/py-1.11.0-3/.self/lib/python3.10/vendor-packages/py-1.11.0-py3.10.egg-info`

**Comment by Begasus** [comment]
The hint on toml and git for setuptools_scm was great, solved half of the issues here! So thank you also! :)
