### ISSUE TITLE
Drop support for Python 3.7

### ISSUE THREAD

**Issue by OscarL** [haikuports/haikuports#8025]
~As beta4 uses Python 3.9 as default, and as Python versions 3.7 and 3.8 are in "Source-only security fix releases" mode (with even less than 3 months of that for 3.7), we should drop support for the older ones (adding support for Python 3.10 where possible).~ Edit: scope for this issue has changed following discussion on comments below.

As beta4 uses Python 3.9 as default, and as Python versions 3.7 is nearing EOL, we'll be dropping support for it (and also for Python 2.7 package that might still remain), while adding support for Python 3.10 where possible.

To help keep track of the progress on this regard, I'll add some tasks list:

## Regular packages (recipes not under `dev-python/`):

List of *. recipes that contain either of:

	- "cmd:python3.7"
	- "_python3$"
	- "libpython.*m"

(and for Python 2.x: `_python$`, `cmd:python$` and `libpython2`)

- [x] aquaskk (Python 2.x) #8780
- [x] atk (Python 2.x) #8768
- [x] aflplusplus #8730
- [x] automake #8517
- [x] bakefile (Python 2.x) #9214
- [x] BeCJK (Python 2) #8499
- [x] bliss060 (Python 2.x) #9210
- [x] brotli #8221
- [x] bzr (Python 2.x) #9172
- [x] caffe (Python support is disabled on the recipe already)
- [x] calibre
- [x] calligra (Python 2.x) #9226
- [x] cegui #8701
- [x] chocolate_doom (Python 2.x) #8772
- [x] command_not_found (Python 2.x) #8497
- [x] cram (Python 2.7 and 3.7) #8725
- [x] crawl
- [ ] csound (Python 2.x)
- [x] cudatext #8732
- [x] dblatex #8702
- [x] distcc #8519
- [ ] edk2 (Python 2.x)
- [x] fife (Python 2.x,) (see #8840 / #8839)
- [x] fontforge #8239
- [x] glances #8171
- [x] glib2 (Python 2.x) #9191
- [x] gmsh #8430
- [x] graphviz #8241
- [x] grpc (Python2.x and 3.x, only for TEST(), marked broken on 32 bits) #8752
- [x] gtest #8718
- [x] gyp (Python 2.x) #8779
- [ ] handbrake (Python 2.x)
- [x] hugen (Python 2.x) #8502
- [x] iniparse (Python 2.x) #9189
- [x] itstool (Python 2.x) #8605
- [x] json_glib #8505
- [ ] kdb (Python 2.x)
- [x] kotatogram #8524
- [ ] ktorrent (Python 2.x)
- [x] lapack #8503
- [x] libpurple #8715
- [x] libcec #8302
- [x] libepoxy #8714
- [x] libsigrokdecode #8442
- [x] libktorrent #8308
- [x] libmypaint #8384
- [x] libreoffice 6.4 (Python 2.7 and 3.7) #9228
- [x] libreoffice 7.3 #8613 and #9218
- [x] libsvm (Python 2.x) #9192
- [x] libxml2 (Python 2.x) 15c66cd7270bd28f645f74009f99ae0769bd6efb
- [x] llvm12 #8413
- [x] llvm9 #8614
- [x] masterpiece (Python 2.7) #9175 (recipe disabled?)
- [x] mozc (see issue #8767) #8845
- [x] mpd
- [ ] nodejs12 (Python 2.x) #9234
- [ ] noteshrink (Python 2.x) #8770
- [x] opencolorio #8719
- [x] opencv #8594
- [x] opencv3 #8571
- [x] opensubdiv (python2): #8102 (and #9193)
- [x] orphilia_dropbox #8084
- [x] partio #8441
- [x] poezio #8037
- [ ] poppler (Python 2.x)
- [x] python2.7 (So long 2.7!!!) #9176
- [x] python3.7 (duh!) #9229
- [x] qgis #8734
- [x] qt6_3d
- [x] qt6_5compat
- [x] qt6_base
- [x] qt6_charts
- [x] qt6_connectivity
- [x] qt6_datavis3d
- [x] qt6_declarative
- [x] qt6_imageformats
- [x] qt6_lottie
- [x] qt6_multimedia
- [x] qt6_networkauth
- [x] qt6_positioning
- [x] qt6_quick3d
- [x] qt6_quicktimeline
- [x] qt6_scxml
- [x] qt6_sensors
- [x] qt6_serialport #8195
- [x] qt6_shadertools #8192
- [x] qt6_svg
- [x] qt6_tools
- [x] qt6_translations
- [x] qt6_webchannel
- [x] qt6_websockets
- [x] ranger (Python 2.7 and 3.7) #8721
- [x] rizin #8704 (and again on #8764)
- [ ] rust (Python 2.x)
- [x] sane_backends #8543
- [x] schismtracker #8473
- [x] scribus #9213
- [x] sigil #8096
- [x] spice #8703
- [x] suitesparse (Python 2.x) #9235
- [x] swift_lang (Python 2.x) (see #8838 / #8837)
- [x] thepowdertoy #8700
- [x] u-boot #8766
- [x] youcompleteme (only for older, disabled recipes, new one uses 3.9).

## Python packages (recipes under `dev-python/`):

 List of `*.recipe` files for Python packages that contain either of:

	- "PYTHON_VERSIONS*=(3.7"
	- "(python)"
	- "PYTHON_PACKAGES*=(python3)"
	- "PYTHON_PACKAGES*=(python python3"
	- "_python3$".

(and for Python 2.x: _python$ and cmd:python$)

- [x] aiodns #8077
- [x] aiohttp #8049
- [x] aiohttp_socks #8079
- [x] aiorpcx #8080
- [x] aiosignal #8051
- [x] alembic_py #8082
- [x] apply_defaults #8081
- [x] apsw
- [x] argh #8085
- [x] asn1crypto
- [x] astroid
- [x] async_timeout #8053
- [x] asynctest #8054
- [x] atomicwrites
- [x] attrs
- [x] babel
- [x] backports_tempfile (also: #8119)
- [x] backports_weakref (also: #8120)
- [x] bcrypt #8030
- [x] beautifulsoup
- [x] bitlbee #8516
- [x] bitstring
- [x] bottle
- [x] build
- [x] certifi
- [x] cffi #8043
- [x] chardet
- [x] charset_normalizer #8052
- [x] click
- [x] colorama
- [x] constantly
- [x] coverage #8148
- [x] cryptography #8029
- [x] cryptography_vectors #8242
- [x] css_parser
- [x] cssselect #8095
- [x] cython
- [x] dateutil
- [x] decorator
- [x] discid
- [x] dnspython
- [x] docutils
- [x] dukpy
- [x] dulwich
- [x] ecdsa
- [x] editor
- [x] editorconfig_core_py
- [x] enum34 (Python 2) #8151
- [x] fasteners
- [x] feedparser
- [x] flake8
- [x] flit
- [x] flit_core
- [x] fluidity_sm
- [x] fonttools
- [x] frozendict
- [x] frozenlist #8045
- [x] funcsigs (Python 2) #8225
- [x] future
- [x] futures (Python 2) #8224
- [x] gdata (Python 2) #8228
- [x] gitdb
- [x] html2text
- [x] html5_parser #8173
- [x] html5lib
- [x] httplib2
- [x] hyperlink
- [x] idna
- [x] ifaddr
- [x] imagesize_py
- [x] importlib_metadata
- [x] importlib_resources
- [x] imutils #8092
- [x] incremental
- [x] iniconfig
- [x] installer
- [x] jdtranslationhelper
- [x] jinja
- [x] jsonrpcclient #8209
- [x] jsonrpcserver #8204
- [x] jsonschema #8189
- [x] kiwisolver
- [x] lexicon
- [x] lxml #8093
- [x] mako
- [x] markdown
- [x] markdown_math
- [x] markups
- [x] markupsafe
- [x] mccabe
- [x] mechanize
- [x] mock
- [x] more_itertools
- [x] msgpack
- [x] multidict #8046
- [x] mutagen
- [x] networkx
- [x] node_semver
- [x] nose
- [x] packaging
- [x] parameterized
- [x] paramiko #8026
- [x] patch_ng
- [x] pathtools
- [x] pep517
- [x] pep8
- [x] pillow
- [x] pip
- [x] ply
- [x] polib
- [x] pretend
- [x] psutil #8172
- [x] pyaes (Python 2.7 and 3.7) #8249
- [x] pyasn1
- [x] pyasn1_modules
- [x] pybind11
- [x] pycares #8035
- [x] pychart #8183
- [x] pycodestyle
- [x] pycparser
- [x] pycrypto
- [x] pycurl #8220
- [x] pydispatcher  (Python 2) #8230
- [x] pyenchant
- [x] pyflakes
- [x] pygame #8255 #8257
- [x] pygments
- [x] pyjwt
- [x] pylzma #8213
- [x] pymupdf
- [x] pynacl #8027
- [x] pyopengl #8211
- [x] pyopenssl
- [x] pypandoc
- [x] pyparsing
- [x] pypeg2
- [x] pyqt_builder #8231
- [x] pyrsistent
- [x] pyrfc3339
- [x] pyserial
- [x] pytest #8011
- [x] pytest_mock #8012
- [x] pytest_relaxed #8013
- [x] python_distutils_extra
- [x] python_graphviz
- [x] python_imaging (Python 2.7) #8773
- [x] python_ly
- [x] python_markdown_math
- [x] python_pkgconfig
- [x] pythonzeroconf
- [x] pytz
- [x] pywebsocket (Python 2.7) #8769
- [x] pyyaml
- [x] qrcode
- [x] rdflib
- [x] regex
- [x] reportlab
- [x] requests
- [x] setuptools
- [x] setuptools_scm
- [x] six
- [x] slixmpp #8036
- [x] smartypants
- [x] smmap
- [x] soupesieve
- [x] sqlalchemy
- [x] svgwrite
- [x] toml
- [x] tomli
- [x] tqdm
- [x] typing_extensions
- [x] typogrify
- [x] tzlocal
- [x] urllib3
- [x] urwid
- [x] voluptuous
- [x] waitress
- [x] watchdog
- [x] webencodings
- [x] wheel
- [x] whichcraft
- [x] wrapt
- [x] yarl #8047
- [x] zipp
- [x] zope_interface

**Comment by korli** [comment]
python 3.8 is still supported whatever you understand.

**Comment by korli** [comment]
You wrote "Python versions 3.7 and 3.8 are in "Source-only security fix releases" mode" as a reason for this issue. But only 3.7 is soon EOL. We switched to 3.9 only three months ago, please give users some time before removing anything.

**Comment by korli** [comment]
> Alright.
> 
> Guess moving low impact packages from 3.7 to 3.9 would still be OK? Or would you rather prefer to see PRs that only add 3.9/3.10 support if missing?

Sure, moving away from 3.7 when upgrading versions is OK.

**Comment by korli** [comment]
IMO it's irrelevant when Beta 4 switched to Python 3.9 as the new default. If users use Python 3.8 and vendor packages for their own python scripts, they should be given some time to upgrade (6 months seem reasonable). Python 3.7 won't be supported long upstream, so that's another case. 
Issuing a warning on the forums is also an idea.

**Comment by Begasus** [comment]
@threedeyes most of the qt packages are still using python3.7, did a few already (see list above), any reason why python is involved in them? (haven't seen any mention in the configure/build process?)

For qmdnsengine I can't find any reference to python aside from some doxygen references?
https://github.com/nitroshare/qmdnsengine/search?q=python

**Comment by Begasus** [comment]
https://github.com/haikuports/haikuports/pull/8302

**Comment by pulkomandy** [comment]
> Haikuporter complains that the there's a patchset file not being referenced from the recipe. ("solved" it temporarily by renaming it, just to test).

It seems I just forgot the PATCHES in the recipe and that should be added, rather than ignoring the patch?

I had this working when I pushed it, otherwise I would have marked the recipe as broken. I have used the resulting uboot binaries on an ARM system and managed to get haiku_loader running with it.

The first problem appears to be a missing dependency of arm-none-eabi-gcc to lib:libmpfr$secondaryArchSuffix.

Also I'm a bit confused why you ask this in a thread about Python 3.7?

**Comment by pulkomandy** [comment]
From the list in the initial post I think "only" scribus and libreoffice are still on Python 3.7? Is there anything else?

**Comment by Begasus** [comment]
I think this can be closed, yielding with "inrecipe ..." doesn't show up anything for python3.7, cmd:python3 is only used in BUILD_PREREQUIRES so installing those packages shouldn't be a problem, rebuilding them for a newer version will use python3.10 at this moment.
