### ISSUE TITLE
[python packages] Provide "non _x86" package name where needed.

### ISSUE THREAD

**Issue by OscarL** [haikuports/haikuports#8806]
On 32 bits, Python modules that require compilation (or depend on compiled libraries) should PROVIDE not only the regular `*_x86_python3*`, but also a `*_python3*` package name.

----

List of recipes under `dev-python/` that should (or already do) also PROVIDE "non _x86" packages.

- [x] aiohttp-3.8.1 *
- [x] apsw-3.36.0~r1 *
- [x] argon2_cffi_bindings-21.2.0 #8808
- [x] bcrypt-3.2.0 *
- [x] cffi-1.15.1 *
- [x] coverage-7.2.2
- [x] cryptography-3.3.2
- [x] cython-0.29.32
- [x] dbuspython-1.2.14 #8809
- [x] dukpy-0.3 #8810
- [x] dulwich-0.20.32 *
- [x] frozenlist-1.3.1 *
- [x] html5_parser-0.4.10
- [x] kiwisolver-1.3.1 *
- [x] lazy_object_proxy-1.5.2 #8811
- [x] lxml-4.9.1 *
- [x] matplotlib-3.3.4 #8882
- [x] multidict-4.5.2 *
- [x] numpy-1.23.3 *
- [ ] pandas-1.3.2
- [x] paramiko-2.11.0 (should switch to "any") #10765
- [x] pillow-9.2.0 (wrongly provides "projectx_python*" :-D) #8812
- [x] psutil-5.6.7 #8814
- [x] pyaes-1.6.1 (just needs a cleanup after `pycryptodome` provides "non _x86") #8823
- [x] pybind11-2.6.2 #8822
- [x] pycares-3.1.1 *
- [x] pycrypto-2.6.1 *
- [x] pycryptodome-3.17 #8813
- [x] pycryptodomex-3.17 #8813
- [x] pycurl-7.45.2 #8814
- [x] pyenchant-3.2.2 *
- [x] pygame-2.0.0 #8821
- [x] pylzma-0.5.0
- [x] pymupdf-1.20.2 #8819
- [x] pynacl-1.5.0 *
- [x] pyopenssl-22.0.0 #8817
- [x] pyqt5-5.15.9 **
- [x] pyqt5_sip-12.12.1 *** #9482
- [x] pyqtwebengine5-5.15.6 **
- [x] python_graphviz-0.20.1 *
- [x] python_poppler_qt5-21.3.0 **
- [x] pyzmq-18.1.0 *
- [x] qrcode-7.2 #8818
- [x] regex-2020.1.8 #8816
- [x] reportlab-3.6.9 #8815
- [x] scipy-1.6.3 #10706
- [x] sip-6.7.9 *** #9464
- [x] sqlalchemy-1.3.22 *** #9328
- [x] twisted-22.8.0 #8820
- [x] unrardll-0.1.4 *** #9328
- [x] yarl-1.6.3 *

Notes:
- [ ] `*` Could use a recipe cleanup (`"\n\"` removal, for example)
- [ ] `**` Could use (or fix/improve usage of) $pythonVersion.
- [x] `***` Should use "eval" for the "non _x86" PROVIDES.
