### ISSUE TITLE
Failed builds (of python packages) on builds: 5048 (32 bits) and 9391 (64 bits)

### ISSUE THREAD

**Issue by OscarL** [haikuports/haikuports#9345]
Just to help keep track of things...

64 bits Buildmaster report for [build 9391](https://build.haiku-os.org/buildmaster/master/x86_64/?buildrunDir=9391). (most of those already fixed)
32 bits Buildmaster report for [build 5048](https://build.haiku-os.org/buildmaster/master/x86_gcc2/?buildrunDir=5048).

---

For 32 bits:

- [x] numpy: Seems there are left overs from the previous crash/hang of the buildmaster?

  > Cleaning up temporary directories ...
  unmount: unmounting failed: Device/File/Resource busy

  and then...

  > Cleaning work directory of numpy_x86-1.23.3 ...
  [Errno -2147459064] Read-only file system: '.self'

  Seems to point in that direction, I think.  

The followning five will be fixed with just a rev-bump. They were fixed already on 64 bits, but as 32 bits buildmaster failed previous run, it had an older revision for `setuptools_scm` when building these ones.

- [x] importlib_resources
- [x] iniconfig
- [x] pyparsing
- [x] zipp

Fixed on #9349

---

For both 32 and 64 bits:

- [x] constantly: Need to analyze this one further. #9368
- [x] feedparser: should be updated to at least 6.0.1 (after removal of all Python 2.x support there).
  This needs a new recipe for [sgmllib3k](https://pypi.org/project/sgmllib3k/) (a VERY OLD and unmaintained package, sigh). #9366 and #9367
- [x] installer: missing `flit_core` dependency. #9369
- [x] scipy: this needs a recipe update, but that needs libgfortran.so getting fixed first.
- [x] tqdm: should be updated and built with build/installer. #9363 and #9372
